### PR TITLE
[PR against gabrielgellner master, i.e. the PR branch for  #14] Additional fixes for 1.0

### PR DESCRIPTION
**Pull request by tkoolen**
This updates the Travis configuration and gets most of the tests to pass. @rdeits, I decided to drop NonnegLeastSquares as a test dependency for now (although 0.7/1.0 support for it is close). The remaining issue is the zero allocation tests involving `@wrappedallocs`. @gabrielgellner, would you happen to have time to look into what's going on with those?

### CODE REVIEW

**Comment by gabrielgellner** [comment]
I will look into the `@wrappedallocs`

**Comment by gabrielgellner** [comment]
Soooo do I merge this pull then fix the `@wrap` issue and make another pull request? My gitfu is weak :)

**Comment by tkoolen** [comment]
You did the right thing :slightly_smiling_face:.

**Comment by gabrielgellner** [comment]
Is there any documentation for getting the gfortan / julia stuff working in windows? I have only done that in Linux before, which I don't have access to at the moment :(

**Comment by tkoolen** [comment]
I'd take a look at what Ipopt.jl is doing in their `build.jl`, since they depend on `gfortran` as well: https://github.com/JuliaOpt/Ipopt.jl/blob/master/deps/build.jl.

**Pull request merged**
